### ISSUE TITLE
Duplicate dict key (notify)

### ISSUE THREAD

**Issue by luissquall** [Stouts/Stouts.timezone#4]
After installing ansible 2.0 I noticed this warning:

```
TASK [Stouts.timezone : include] ***********************************************
 [WARNING]: While constructing a mapping from /Users/mono/projects/contadrop/ansible-playbooks/vendor/Stouts.timezone/tasks/timezone.yml, line 31, column 3, found a duplicate dict key (notify).
Using last defined value only.
```

The warning refers to the double `notify` declaration in [timezone.yml](https://github.com/Stouts/Stouts.timezone/blob/develop/tasks/timezone.yml#L33)

I think the solution is as simple as the following and, reading the [docs](http://docs.ansible.com/ansible/playbooks_intro.html#handlers-running-operations-on-change), it is not a 2.0 thing:

``` yaml
  notify:
    - timezone deb_update
    - restart dependent services
```

What do you think? Would you accept a MR?

**Comment by luissquall** [comment]
Any thoughts @klen?

**Comment by klen** [comment]
Fixed, thank you.
